/**
 * Message protocol between the page hook (MAIN world), the bridge content
 * script, the background relay and the DevTools panel.
 *
 * page hook ──window.postMessage──▶ bridge ──runtime.sendMessage──▶ background ──Port──▶ panel
 * panel ──Port──▶ background ──tabs.sendMessage──▶ bridge ──window.postMessage──▶ page hook
 */

import type { ContentState, HarEntry, NetEntry } from '../panel/network/store';

export const SOURCE = 'devkit';
export const SET_STATE = '@@DEVKIT/SET_STATE';

export type StoreMode = 'hooked' | 'limited';

export interface StoreInfo {
  id: string;
  name: string;
  mode: StoreMode;
  paused: boolean;
  /** Entry id the store state was jumped to, or null when showing the live state. */
  jumpedTo: number | null;
}

export interface ActionSummary {
  id: number;
  type: string;
  ts: number;
}

export interface StoreHistory {
  entries: ActionSummary[];
}

export type EntryPart = 'action' | 'state' | 'diff';

/** A change in a diff, with before/after values already serialized. */
export interface SerializedChange {
  path: (string | number)[];
  kind: 'added' | 'removed' | 'changed';
  before?: unknown;
  after?: unknown;
}

export interface ReduxRequestMap {
  init: { params: void; result: { stores: StoreInfo[]; histories: Record<string, StoreHistory> } };
  detect: { params: void; result: { stores: StoreInfo[] } };
  getEntry: { params: { storeId: string; entryId: number; part: EntryPart }; result: unknown };
  /** Ids of history entries whose type or action contents contain every whitespace separated term. */
  filterActions: { params: { storeId: string; query: string }; result: { ids: number[] } };
  getState: { params: { storeId: string }; result: unknown };
  dispatch: { params: { storeId: string; action: unknown }; result: null };
  jump: { params: { storeId: string; entryId: number }; result: null };
  resume: { params: { storeId: string }; result: null };
  importState: { params: { storeId: string; state: unknown }; result: null };
  clearHistory: { params: { storeId: string }; result: null };
  setPaused: { params: { storeId: string; paused: boolean }; result: null };
}

export type ReduxRequestMethod = keyof ReduxRequestMap;

/** How a form's values are read and written: through redux-form or through the DOM. */
export type FormKind = 'redux-form' | 'dom';

export interface FormField {
  /** redux-form field name (`address.street`, `items[0].code`) or DOM field key. */
  path: string;
  /** Field kind for the UI: `Field`, `FieldArray` or a DOM control type. */
  kind: string;
  /** Current value, serialized. */
  value: unknown;
  /** True when the value differs from the form's initial value (redux-form only). */
  dirty?: boolean;
  /** False when the value cannot be restored, e.g. a File. */
  restorable: boolean;
}

export interface DetectedForm {
  /** Addresses the form in a fill request, e.g. `rf:store-1:signup` or `dom:1`. */
  id: string;
  kind: FormKind;
  /** Form name shown in the UI: the redux-form name or a DOM form label. */
  name: string;
  /** Identity used to match saved recordings, see panel/forms/match.ts. */
  key: string;
  /** Extra context for the UI: store name and mount key, or the form's selector. */
  detail?: string;
  fields: FormField[];
}

export interface FillEntry {
  path: string;
  /** Value to write, serialized. */
  value: unknown;
}

export interface FillResult {
  filled: string[];
  skipped: { path: string; reason: string }[];
}

export interface FormRequestMap {
  'forms/list': { params: void; result: { forms: DetectedForm[]; url: string } };
  /** Writes `entries` into the form; `touch` also marks the fields touched so validation shows. */
  'forms/fill': { params: { formId: string; entries: FillEntry[]; touch: boolean }; result: FillResult };
}

export type FormRequestMethod = keyof FormRequestMap;

export type RequestMap = ReduxRequestMap & FormRequestMap;

export type RequestMethod = keyof RequestMap;

export function isFormMethod(method: RequestMethod): method is FormRequestMethod {
  return method.startsWith('forms/');
}

export interface PageRequest<M extends RequestMethod = RequestMethod> {
  kind: 'request';
  requestId: number;
  method: M;
  params: RequestMap[M]['params'];
}

/** Messages from the page hook to the panel. */
export type PageEvent =
  | { kind: 'response'; requestId: number; ok: true; result: unknown }
  | { kind: 'response'; requestId: number; ok: false; error: string }
  | { kind: 'store-added'; store: StoreInfo }
  | { kind: 'store-updated'; store: StoreInfo }
  | { kind: 'actions'; storeId: string; entries: ActionSummary[]; minId: number }
  | { kind: 'history-cleared'; storeId: string; entries: ActionSummary[] };

/** Messages generated by the background relay itself. */
export type RelayEvent = { kind: 'page-unavailable'; requestId?: number; error: string };

export type PanelInbound = PageEvent | RelayEvent;
export type PanelOutbound = PageRequest | { kind: 'ping' };

/**
 * Full capture: the DevTools page opens a `capture:<tabId>` port and the background
 * records the tab's network traffic with `chrome.debugger` until the port closes.
 */
export const CAPTURE_PORT_PREFIX = 'capture:';

export type CaptureCommand = { kind: 'start'; maxBodyMB: number };

export type CaptureEvent =
  | { kind: 'entry'; har: HarEntry; contentState: ContentState; content?: NetEntry['content'] }
  | { kind: 'detached'; reason: string }
  | { kind: 'error'; message: string };

export interface Envelope<T> {
  source: typeof SOURCE;
  payload: T;
}

export interface WindowEnvelope<T> extends Envelope<T> {
  dir: 'to-page' | 'to-panel';
}

export function isEnvelope(value: unknown): value is Envelope<unknown> {
  return typeof value === 'object' && value !== null && (value as Envelope<unknown>).source === SOURCE;
}

export function isWindowEnvelope(value: unknown, dir: WindowEnvelope<unknown>['dir']): value is WindowEnvelope<unknown> {
  return isEnvelope(value) && (value as WindowEnvelope<unknown>).dir === dir;
}
